Sliding door: Kinematic Character Controller to report trigger contacts
rbfx/rbfx pull request #583
Opened 2023-07-04 14:46 UTC by gleblebedev

Kinematic Character Controller now reports trigger contacts
A sample trigger in character samples
New component to handle trigger interactions and play animations accordingly
Sample prefab with a sliding door for Character Controller and Kinematic Character Controller samples

2023-07-04 15:07 UTC, 1vanK commented on Source/Urho3D/Physics/KinematicCharacterController.h
> +#include "Urho3D/Physics//RigidBody.h"
//

2023-07-16 09:08 UTC, eugeneko requested changes

2023-07-16 09:08 UTC, eugeneko commented on Source/Urho3D/Physics/TriggerAnimator.cpp
> +void TriggerAnimator::HandlePhysicsCollisionStart(StringHash eventType, VariantMap& eventData)
I don't like M*N complexity. All triggers process all collisions and then ignore most of them.
They should subscribe only to relevant Node instead.
Other than that, it looks okay.

2023-07-17 08:02 UTC, eugeneko commented on Source/Urho3D/Physics/TriggerAnimator.cpp
> +            UnsubscribeFromEvent(E_PHYSICSCOLLISIONSTART);
Wrong event used

2023-07-23 17:58 UTC, eugeneko approved these changes

2023-07-23 20:38 UTC, merged